---
title: "Data pre-processing & Data splitting"
author: "Andrew Kim"
date: "6/22/2022"
output: html_document
---

__This notebook contains the data splitting procedure for the tree cover type data set.__

```{r}
library(ggplot2)
library(dplyr)
library(caret)
library(AppliedPredictiveModeling)
set.seed(0)
```

```{r}
df = read.csv("../data/covertype.csv")
head(df)
```

```{r}
str(df)
```

```{r}
summary(df)
```

```{r}
# Checking for missing values
sum(is.na(df))
```
__There are no missing (NA) values in each feature.__

```{r}
# Remove features/predictors with no variance
zero_cols <- nearZeroVar(df)
print(zero_cols)
df <- df[, -zero_cols]
```

```{r}
# Convert the Cover_type variable into a factor variable. This will generate this variable into seven levels.
df$Cover_Type <- as.factor(df$Cover_Type)
str(df)
```

```{r}
### checking for high correlations
df_Cor =  cor(df[,1:9])
highCors = findCorrelation(df_Cor , cutoff = .75)
print(highCors)
df = df[,-highCors]
```

```{r}
pairs(df_Cor)
```

```{r}
# Split the data into training and testing sets (80% and 20%).
ctraining <- createDataPartition(df$Cover_Type, p = 0.8, list = FALSE)

train <- df[ctraining, ]
test <- df[-ctraining, ]
```

```{r}
### Class rebalancing on training set.
train <- downSample(x = train[, -ncol(train)], 
                    y = train$Cover_Type,
                    yname = "Cover_Type") 
```

```{r}
### Writing train/test split to csv for modeling
write.csv(train,"../data/train.csv", row.names = FALSE)
write.csv(test,"../data/test.csv", row.names = FALSE)
```

```{r}
train = read.table("../data/train.csv", sep = ",", header=TRUE)
test = read.table("../data/test.csv", sep = ",", header=TRUE)
```

```{r}
colnames(train)
```

```{r}
# Grouping soil type variables into one group
library(dplyr)
soil_group <- train %>%
  group_by(Soil_Type10, Soil_Type12, Soil_Type22, Soil_Type23, Soil_Type29, 
           Soil_Type30, Soil_Type32, Soil_Type33) %>%
  dplyr::summarise(soil_sum = sum(Cover_Type)) %>% 
  as.data.frame()
```

```{r}
# Grouping wilderness area variables into one group
wilderness_group <- train %>%
  group_by(Wilderness_Area1, Wilderness_Area2, Wilderness_Area3, Wilderness_Area4) %>%
  dplyr::summarise(wilderness_sum = sum(Cover_Type)) %>% 
  as.data.frame()
```

```{r}
# Evaluating Euclidean & Manhattan distances of soil types
dist(soil_group, method = 'euclidean')
dist(soil_group, method = "manhattan")
```

```{r}
# Evaluating Euclidean & Manhattan distances of wilderness areas
dist(wilderness_group, method = 'euclidean')
dist(wilderness_group, method = "manhattan")
```







