---
title: "Data pre-processing & Data splitting"
author: "Andrew Kim"
date: "6/22/2022"
output: html_document
---

__This notebook contains the data splitting procedure for the tree cover type data set.__

```{r}
library(ggplot2)
library(dplyr)
library(caret)
library(AppliedPredictiveModeling)
set.seed(0)
```

```{r}
df = read.csv("C:/Users/andre/OneDrive/Desktop/ADS503/covtype.csv")
head(df)
```

```{r}
str(df)
```

```{r}
summary(df)
```

```{r}
# Count the number of NA's in each feature
apply(df, 2, function(x){sum(is.na(x))})
```

__There are no missing (NA) values in each feature.__

```{r}
# Check for predictors that are highly correlated
correlations <- cor(df)
dim(df)
```

```{r}
library(corrplot)
corrplot(correlations)
```

```{r}
# Pre-process the data
library(caret)
Cov_type <- preProcess(df, method = c("center", "scale"))
Cov_type
```

```{r}
# Apply the transformations to the original dataset
Cov_transformed <- predict(Cov_type, df)
head(Cov_transformed)
```

```{r}
# Find the predictors that are highly correlated within the dataset
zero_cols <- nearZeroVar(Cov_transformed)
colnames(Cov_transformed[zero_cols])
```

```{r}
# Eliminate the highly correlated predictors from further consideration
Covtype <- Cov_transformed[, -zero_cols]
Covtype
```

```{r}
# Convert Cover_Type variable into a factor variable. This will factor the variable to seven categories
Covtype$Cover_Type <- as.factor(Covtype$Cover_Type)
str(Covtype)
```

```{r}
# Split the data into training and testing sets (80% and 20%).
ctraining <- createDataPartition(Covtype$Cover, p = 0.8, list = FALSE)

covtype_train <- Covtype[ctraining, ]
covtype_test <- Covtype[-ctraining, ]
```








