---
title: "Untitled"
author: "Andrew Kim"
date: "6/21/2022"
output: html_document
---

__This notebook contains the data splitting procedure for the tree cover type data set.__

```{r}
library(ggplot2)
library(dplyr)
library(caret)
set.seed(0)
```

```{r}
df = read.csv("C:/Users/andre/OneDrive/Desktop/ADS503/covtype.csv")
head(df)
```

```{r}
str(df)
```

```{r}
summary(df)
```

```{r}
# Count the number of NA's in each feature
apply(df, 2, function(x){sum(is.na(x))})
```

```{r}
# Find and search for categorical variables/features that possess no variance
zero_cols <- nearZeroVar(df)
colnames(df[zero_cols])

# Remove variables/features with no variance
Covtype <- df[, -zero_cols]
Covtype
```

```{r}
# Convert the Cover_type variable into a factor variable. This will generate this variable into seven levels.
Covtype$Cover_Type <- as.factor(Covtype$Cover_Type)
str(Covtype)
```

```{r}
# Split the data into training and testing sets (80% and 20%).
ctraining <- createDataPartition(Covtype$Cover, p = 0.8, list = FALSE)

covtype_train <- Covtype[ctraining, ]
covtype_test <- Covtype[-ctraining, ]
```








