---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height =8)
knitr::opts_chunk$set(cache = TRUE)
options(scipen=999)
```

```{r}
library(doParallel)
cl <- makePSOCKcluster(4)
registerDoParallel(cl)
library(mlbench)
library(nnet)
library(pROC)
library(MASS)
library(pamr)
library(rpart)
library(mda)
library(earth)
library(randomForest)
library(xgboost)
library(caret)
```

```{r}
train = read.table("../data/train.csv",
                   sep = ",",
                   header = TRUE)

test = read.table("../data/test.csv",
                  sep = ",",
                  header = TRUE)
```

```{r}
str(train)
```
```{r}
train$Cover_Type <- as.factor(train$Cover_Type)
test$Cover_Type <- as.factor(test$Cover_Type)
levels(train$Cover_Type) <- c("Spruce.Fir", "Lodgepole.Pine", "Ponderosa.Pine", "Cottonwood.Willow", "Aspen", "Douglas.fir", "Krummholz")
levels(test$Cover_Type) <- c("Spruce.Fir", "Lodgepole.Pine", "Ponderosa.Pine", "Cottonwood.Willow", "Aspen", "Douglas.fir", "Krummholz")
```


```{r}
set.seed(7)
ctrl = trainControl(summaryFunction = multiClassSummary,
                    classProbs = TRUE)
```

```{r}
lrFit = train(Cover_Type~., 
               data = train,
               method = "multinom",
               preProc = c("center", "scale","BoxCox"))
lrFit
```
```{r}
lrFit_pred = predict(lrFit, test)
postResample(pred = lrFit_pred, obs = test$Cover_Type)
```
```{r}
varImp(lrFit, scale = FALSE)
```

```{r}
gbmFit = train(Cover_Type~., 
               data = train,
               method = "gbm",
               preProc = c("center", "scale","BoxCox"))
gbmFit
```
```{r}
gbmFit_pred = predict(gbmFit, test)
postResample(pred = gbmFit_pred, obs = test$Cover_Type)
```
```{r}
summary(gbmFit)
```

```{r}
rfFit = train(Cover_Type~., 
              data = train,
              method = "rf",
              preProc = c("center", "scale","BoxCox"),
              metric = "Accuracy",           
              trControl = ctrl)
rfFit
```

```{r}
rfFit_pred = predict(rfFit, test)
postResample(pred = rfFit_pred, obs = test$Cover_Type)
```
```{r}
varImp(rfFit, scale = FALSE)
```

```{r}
xgbFit = train(Cover_Type~., 
               data = train,
               method = "xgbTree",
               preProc = c("center", "scale","BoxCox"),
               metric = "Accuracy",
               trControl = ctrl)
xgbFit
```

```{r}
xgbFit_pred = predict(xgbFit, test)
postResample(pred = xgbFit_pred, obs = test$Cover_Type)
```
```{r}
varImp(xgbFit, scale = FALSE)
```



