---
title: "v2_baseline_resampling_validation"
output: html_notebook
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height =8)
knitr::opts_chunk$set(cache = TRUE)
options(scipen=999)
memory.limit(size=56000)
```

```{r}
library(doParallel)
cl <- makePSOCKcluster(4)
registerDoParallel(cl)
library(mlbench)
library(ROSE)
library(performanceEstimation)
library(nnet)
library(pROC)
library(MASS)
library(pamr)
library(rpart)
library(mda)
library(earth)
library(randomForest)
library(xgboost)
library(caret)
```

```{r}
train = read.table("../data/train_no_rebal.csv",
                   sep = ",",
                   header = TRUE)

test = read.table("../data/test_no_rebal.csv",
                   sep = ",",
                   header = TRUE)
```

```{r}
str(train)
```
```{r}
train$Cover_Type <- as.factor(train$Cover_Type)
test$Cover_Type <- as.factor(test$Cover_Type)
levels(train$Cover_Type) <- c("Spruce.Fir", "Lodgepole.Pine", "Ponderosa.Pine", "Cottonwood.Willow", "Aspen", "Douglas.fir", "Krummholz")
levels(test$Cover_Type) <- c("Spruce.Fir", "Lodgepole.Pine", "Ponderosa.Pine", "Cottonwood.Willow", "Aspen", "Douglas.fir", "Krummholz")
```

```{r}
set.seed(7)
ctrl = trainControl(summaryFunction = multiClassSummary,
                    classProbs = TRUE)

rfFit = train(Cover_Type~., 
                 data = train,
                 method = "rf",
                 preProc = c("center", "scale","BoxCox"),
                 metric = "Accuracy",           
                 trControl = ctrl)
rfFit
```

```{r}
rfFit_pred = predict(rfFit, test)
postResample(pred = rfFit_pred, obs = test$Cover_Type)
```

```{r}
set.seed(7)
ctrl = trainControl(summaryFunction = multiClassSummary,
                    classProbs = TRUE,
                    sampling = "up")

rfFit_up = train(Cover_Type~., 
                 data = train,
                 method = "rf",
                 preProc = c("center", "scale","BoxCox"),
                 metric = "Accuracy",           
                 trControl = ctrl)
rfFit_up
```

```{r}
rfFit_up_pred = predict(rfFit_up, test)
postResample(pred = rfFit_up_pred, obs = test$Cover_Type)
```

```{r}
set.seed(7)
ctrl = trainControl(summaryFunction = multiClassSummary,
                    classProbs = TRUE,
                    sampling = "down")

rfFit_down = train(Cover_Type~., 
                   data = train,
                   method = "rf",
                   preProc = c("center", "scale","BoxCox"),
                   metric = "Accuracy",           
                   trControl = ctrl)
rfFit_down
```

```{r}
rfFit_down_pred = predict(rfFit_down, test)
postResample(pred = rfFit_down_pred, obs = test$Cover_Type)
```

```{r}
set.seed(7)
ctrl = trainControl(summaryFunction = multiClassSummary,
                    classProbs = TRUE,
                    sampling = "smote")

rfFit_smote = train(Cover_Type~., 
                    data = df,
                    method = "rf",
                    preProc = c("center", "scale","BoxCox"),
                    metric = "Accuracy",           
                    trControl = ctrl)
rfFit_smote
```

```{r}
rfFit_smote_pred = predict(rfFit_smote, test)
postResample(pred = rfFit_smote_pred, obs = test$Cover_Type)
```

